# Generated by Django 3.0.2 on 2020-01-26 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shapefile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
