# Generated by Django 3.0.2 on 2020-01-26 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shapefile', '0002_auto_20200126_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='bara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('palika', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('gapa_napa', models.CharField(max_length=50)),
                ('gn_type', models.CharField(max_length=50)),
                ('province', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
