# Generated by Django 3.0.2 on 2020-01-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shapefile', '0004_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shapefile',
            options={'verbose_name_plural': 'Shapefile'},
        ),
        migrations.RenameField(
            model_name='shapefile',
            old_name='title',
            new_name='name',
        ),
    ]
